.PHONY: serve build deploy

serve:
	hugo server -D

build:
	hugo --gc --cleanDestinationDir

# Builds locally to catch errors early, stages and commits all changes with an
# autogenerated message, then pushes to master. GitHub Actions
# (.github/workflows/deploy.yml) rebuilds and publishes to GitHub Pages on push.
deploy: build
	git add -A
	@if git diff --cached --quiet; then \
		echo "Nothing to commit."; \
	else \
		files=$$(git diff --cached --name-only | tr '\n' ' '); \
		git commit -m "Update: $$files"; \
	fi
	git push origin master
